name: quant_lab
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _py-xgboost-mutex=2.0
  - absl-py=2.1.0
  - aiobotocore=2.15.2
  - aiohappyeyeballs=2.4.4
  - aiohttp=3.11.11
  - aioitertools=0.12.0
  - aiosignal=1.3.2
  - alphalens-reloaded=0.4.3
  - alsa-lib=1.2.13
  - altair=5.5.0
  - anyio=4.7.0
  - aom=3.9.1
  - appdirs=1.4.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - astropy=7.0.0
  - astropy-base=7.0.0
  - astropy-iers-data=0.2024.12.16.0.35.48
  - asttokens=3.0.0
  - astunparse=1.6.3
  - async-lru=2.0.4
  - attr=2.5.1
  - attrs=24.3.0
  - aws-c-auth=0.8.0
  - aws-c-cal=0.8.1
  - aws-c-common=0.10.6
  - aws-c-compression=0.3.0
  - aws-c-event-stream=0.5.0
  - aws-c-http=0.9.2
  - aws-c-io=0.15.3
  - aws-c-mqtt=0.11.0
  - aws-c-s3=0.7.7
  - aws-c-sdkutils=0.2.1
  - aws-checksums=0.2.2
  - aws-crt-cpp=0.29.7
  - aws-sdk-cpp=1.11.458
  - azure-core-cpp=1.14.0
  - azure-identity-cpp=1.10.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - babel=2.16.0
  - beautifulsoup4=4.12.3
  - bleach=6.2.0
  - blinker=1.9.0
  - blosc=1.21.6
  - bokeh=3.6.3
  - botocore=1.35.36
  - bottleneck=1.4.2
  - bqplot=0.12.43
  - branca=0.8.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.4
  - c-blosc2=2.15.2
  - ca-certificates=2025.1.31
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.5.2
  - cairo=1.18.2
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.4.0
  - clarabel=0.7.1
  - click=8.1.7
  - cloudpickle=3.1.0
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.1
  - cpp-expected=1.1.0
  - cpython=3.11.11
  - cvxpy=1.5.3
  - cvxpy-base=1.5.3
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - dask-core=2024.12.1
  - dateparser=1.2.0
  - dav1d=1.2.1
  - dbus=1.13.6
  - debugpy=1.8.11
  - decorator=5.1.1
  - dill=0.3.9
  - ecos=2.0.14
  - entrypoints=0.4
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.4
  - flatbuffers=24.12.23
  - fmt=11.0.2
  - folium=0.20.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.55.3
  - fqdn=1.5.1
  - freetype=2.12.1
  - freexl=2.0.0
  - frozendict=2.4.6
  - frozenlist=1.5.0
  - fsspec=2024.10.0
  - gast=0.4.0
  - geodatasets=2024.8.0
  - geopandas=1.1.1
  - geopandas-base=1.1.1
  - geos=3.13.0
  - geotiff=1.7.4
  - gettext=0.23.1
  - gettext-tools=0.23.1
  - gflags=2.2.2
  - giflib=5.2.2
  - gitdb=4.0.12
  - gitpython=3.1.44
  - glib=2.82.2
  - glib-tools=2.82.2
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.1.5
  - google-pasta=0.2.0
  - graphite2=1.3.13
  - grpcio=1.67.1
  - gst-plugins-base=1.24.7
  - gstreamer=1.24.7
  - h11=0.14.0
  - h2=4.1.0
  - h5py=3.12.1
  - harfbuzz=10.2.0
  - hdf5=1.14.4
  - hmmlearn=0.3.3
  - hpack=4.0.0
  - html5lib=1.1
  - httpcore=1.0.7
  - httpx=0.28.1
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.10
  - imageio=2.36.1
  - importlib-metadata=8.5.0
  - importlib_resources=6.4.5
  - ipydatagrid=1.4.0
  - ipykernel=6.29.5
  - ipympl=0.9.6
  - ipython=8.30.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.1.5
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.4
  - jmespath=1.0.1
  - joblib=1.4.2
  - jplephem=2.21
  - json-c=0.18
  - json5=0.10.0
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.11.0
  - jupyter_server=2.14.2
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.3.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - keras=3.8.0
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.3
  - libarchive=3.7.7
  - libarrow=18.1.0
  - libarrow-acero=18.1.0
  - libarrow-dataset=18.1.0
  - libarrow-substrait=18.1.0
  - libasprintf=0.23.1
  - libasprintf-devel=0.23.1
  - libavif16=1.3.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.71
  - libcblas=3.9.0
  - libclang-cpp19.1=19.1.7
  - libclang13=19.1.7
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=8.11.1
  - libde265=1.0.15
  - libdeflate=1.23
  - libdrm=2.4.124
  - libedit=3.1.20191231
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.4
  - libffi=3.4.2
  - libflac=1.4.3
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgcrypt-lib=1.11.0
  - libgdal-core=3.10.0
  - libgettextpo=0.23.1
  - libgettextpo-devel=0.23.1
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgirepository=1.82.0
  - libgl=1.7.0
  - libglib=2.82.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=14.2.0
  - libgoogle-cloud=2.33.0
  - libgoogle-cloud-storage=2.33.0
  - libgpg-error=1.51
  - libgrpc=1.67.1
  - libheif=1.18.2
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libllvm19=19.1.7
  - liblzma=5.6.3
  - libmamba=2.0.5
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libogg=1.3.5
  - libopenblas=0.3.28
  - libopus=1.3.1
  - libosqp=0.6.3
  - libparquet=18.1.0
  - libpciaccess=0.18
  - libpng=1.6.47
  - libpq=17.2
  - libprotobuf=5.28.3
  - libqdldl=0.1.7
  - libre2-11=2024.07.02
  - librttopo=1.1.0
  - libsndfile=1.2.2
  - libsodium=1.0.20
  - libsolv=0.7.30
  - libspatialite=5.1.0
  - libsqlite=3.49.1
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libsystemd0=257.2
  - libta-lib=0.4.0
  - libthrift=0.21.0
  - libtiff=4.7.0
  - libutf8proc=2.9.0
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp-base=1.4.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxgboost=2.1.4
  - libxkbcommon=1.8.0
  - libxml2=2.13.5
  - libxslt=1.1.39
  - libzlib=1.3.1
  - llvmlite=0.43.0
  - locket=1.0.0
  - logbook=1.8.0
  - lxml=5.3.0
  - lz4-c=1.10.0
  - lzo=2.10
  - mamba=2.0.5
  - mapclassify=2.10.0
  - markdown=3.6
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - minizip=4.0.7
  - mistune=3.0.2
  - ml_dtypes=0.4.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.9
  - mpmath=1.3.0
  - multidict=6.1.0
  - multitasking=0.0.9
  - munkres=1.1.4
  - mypy_extensions=1.0.0
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - namex=0.0.8
  - nbclient=0.10.2
  - nbconvert-core=7.16.4
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - nlohmann_json=3.11.3
  - nomkl=1.0
  - notebook=7.3.1
  - notebook-shim=0.2.4
  - nspr=4.36
  - nss=3.107
  - numba=0.60.0
  - numexpr=2.10.2
  - numpy=1.26.4
  - odfpy=1.4.1
  - openjpeg=2.5.3
  - openldap=2.6.9
  - openssl=3.4.1
  - opt_einsum=3.4.0
  - optree=0.14.0
  - orc=2.0.3
  - osqp=0.6.7.post3
  - overrides=7.7.0
  - packaging=24.2
  - pandas=2.2.2
  - pandas-datareader=0.10.0
  - pandocfilters=1.5.0
  - parso=0.8.4
  - partd=1.4.2
  - patsy=1.0.1
  - pcre2=10.44
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.0.0
  - pip=24.3.1
  - pixman=0.44.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - plotly=5.24.1
  - ply=3.11
  - pooch=1.8.2
  - proj=9.5.1
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.48
  - propcache=0.2.1
  - protobuf=5.28.3
  - psutil=6.1.0
  - psycopg2=2.9.9
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio-client=17.0
  - pure_eval=0.2.3
  - py-cpuinfo=9.0.0
  - py-xgboost=2.1.4
  - py2vega=0.6.1
  - pyarrow=18.1.0
  - pyarrow-core=18.1.0
  - pybind11=2.13.6
  - pybind11-global=2.13.6
  - pycairo=1.27.0
  - pycparser=2.22
  - pydeck=0.8.0
  - pyerfa=2.0.1.5
  - pyfolio-reloaded=0.9.7
  - pygments=2.18.0
  - pygobject=3.50.0
  - pyogrio=0.10.0
  - pyparsing=3.2.0
  - pyproj=3.7.1
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pysocks=1.7.1
  - pytables=3.10.1
  - python=3.11.11
  - python-dateutil=2.9.0.post0
  - python-docx=1.1.2
  - python-fastjsonschema=2.21.1
  - python-flatbuffers=25.2.10
  - python-json-logger=2.0.7
  - python-tzdata=2024.2
  - python_abi=3.11
  - pytz=2024.2
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qdldl-python=0.1.7.post4
  - qhull=2020.2
  - qt-main=5.15.15
  - qtpy=2.4.3
  - quantstats=0.0.62
  - rav1e=0.7.1
  - re2=2024.07.02
  - readline=8.2
  - referencing=0.35.1
  - regex=2024.11.6
  - reproc=14.2.5.post0
  - reproc-cpp=14.2.5.post0
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.9.4
  - riskfolio-lib=6.2.2
  - rpds-py=0.22.3
  - s2n=1.5.10
  - s3fs=2024.10.0
  - schedule=1.2.2
  - scikit-learn=1.6.0
  - scipy=1.14.1
  - scs=3.2.7
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - setuptools=75.6.0
  - shapely=2.0.7
  - simdjson=3.11.3
  - sip=6.7.12
  - six=1.17.0
  - smmap=5.0.2
  - snappy=1.2.1
  - sniffio=1.3.1
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - spdlog=1.14.1
  - spectra-cpp=1.0.1
  - sqlite=3.49.1
  - stack_data=0.6.3
  - statsmodels=0.14.4
  - streamlit=1.45.0
  - svt-av1=3.0.2
  - sympy=1.13.3
  - ta-lib=0.4.32
  - tabulate=0.9.0
  - tenacity=9.0.0
  - tensorboard=2.18.0
  - tensorboard-data-server=0.7.0
  - tensorflow=2.18.0
  - tensorflow-base=2.18.0
  - tensorflow-estimator=2.18.0
  - termcolor=2.5.0
  - terminado=0.18.1
  - threadpoolctl=3.5.0
  - tinycss2=1.4.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.2.1
  - toolz=1.0.0
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - traittypes=0.2.1
  - types-python-dateutil=2.9.0.20241206
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzdata=2024b
  - tzlocal=5.2
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - uriparser=0.9.8
  - urllib3=2.2.3
  - vectorbt=0.26.2
  - watchdog=6.0.0
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - werkzeug=3.1.3
  - wheel=0.45.1
  - widgetsnbextension=4.0.13
  - wrapt=1.17.0
  - x265=3.5
  - xcb-util=0.4.1
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xerces-c=3.2.5
  - xgboost=2.1.4
  - xkeyboard-config=2.43
  - xlsxwriter=3.2.0
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.5
  - xorg-libx11=1.8.11
  - xorg-libxau=1.0.12
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxrender=0.9.12
  - xorg-libxxf86vm=1.1.6
  - xyzservices=2025.1.0
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - yarl=1.18.3
  - yfinance=0.2.54
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zlib-ng=2.2.2
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - adjusttext==1.3.0
      - aiohttp-client-cache==0.11.1
      - aiosqlite==0.20.0
      - alembic==1.14.0
      - annotated-types==0.7.0
      - antropy==0.1.9
      - arch==7.2.0
      - backoff==2.2.1
      - bcolz-zipline==1.2.12
      - bottle==0.13.2
      - cattrs==24.1.2
      - courlan==1.3.2
      - cython==3.0.12
      - deepdiff==8.2.0
      - defusedxml==0.8.0rc2
      - empyrical-reloaded==0.5.11
      - et-xmlfile==2.0.0
      - eventkit==1.0.3
      - exchange-calendars==4.5.6
      - fastapi==0.115.8
      - finvizfinance==1.1.0
      - formulaic==1.1.1
      - freezegun==1.5.1
      - greenlet==3.1.1
      - holidays==0.69
      - htmldate==1.9.3
      - ib-insync==0.9.86
      - inflection==0.5.1
      - iniconfig==2.0.0
      - inscriptis==2.5.3
      - interface-meta==1.3.0
      - intervaltree==3.1.0
      - iso3166==2.1.1
      - iso4217==1.12.20240625
      - itsdangerous==2.2.0
      - justext==3.0.1
      - korean-lunar-calendar==0.3.1
      - lightweight-charts==2.1
      - linearmodels==6.1
      - lru-dict==1.3.0
      - lxml-html-clean==0.4.1
      - mako==1.3.8
      - mizani==0.13.1
      - monotonic==1.6
      - more-itertools==10.6.0
      - multipledispatch==1.0.0
      - multiprocess==0.70.17
      - narwhals==1.33.0
      - nasdaq-data-link==1.0.4
      - omega==1.0.2
      - openbb==4.4.0
      - openbb-alpha-vantage==1.4.0
      - openbb-benzinga==1.4.0
      - openbb-biztoc==1.4.0
      - openbb-bls==1.1.0
      - openbb-cboe==1.4.0
      - openbb-cftc==1.1.0
      - openbb-charting==2.3.0
      - openbb-commodity==1.3.0
      - openbb-core==1.4.0
      - openbb-crypto==1.4.0
      - openbb-currency==1.4.0
      - openbb-deribit==1.0.0
      - openbb-derivatives==1.4.0
      - openbb-ecb==1.4.0
      - openbb-econdb==1.3.0
      - openbb-econometrics==1.5.0
      - openbb-economy==1.4.0
      - openbb-equity==1.4.0
      - openbb-etf==1.4.0
      - openbb-federal-reserve==1.4.0
      - openbb-finra==1.4.0
      - openbb-finviz==1.3.0
      - openbb-fixedincome==1.4.1
      - openbb-fmp==1.4.0
      - openbb-fred==1.4.0
      - openbb-government-us==1.4.0
      - openbb-imf==1.1.0
      - openbb-index==1.4.0
      - openbb-intrinio==1.4.0
      - openbb-multpl==1.1.0
      - openbb-nasdaq==1.4.0
      - openbb-news==1.4.0
      - openbb-oecd==1.4.0
      - openbb-platform-api==1.1.2
      - openbb-polygon==1.4.0
      - openbb-quantitative==1.4.0
      - openbb-regulators==1.4.0
      - openbb-sec==1.4.0
      - openbb-seeking-alpha==1.4.0
      - openbb-stockgrid==1.4.0
      - openbb-technical==1.4.0
      - openbb-tiingo==1.4.0
      - openbb-tmx==1.3.0
      - openbb-tradier==1.3.0
      - openbb-tradingeconomics==1.4.0
      - openbb-us-eia==1.1.0
      - openbb-wsj==1.4.0
      - openbb-yfinance==1.4.0
      - openpyxl==3.1.5
      - orderly-set==5.3.0
      - pandas-flavor==0.6.0
      - pandas-ta==0.3.14b0
      - pathos==0.3.3
      - peewee==3.17.3
      - plotnine==0.14.5
      - pluggy==1.5.0
      - polars==1.26.0
      - posthog==3.12.1
      - pox==0.3.5
      - ppft==1.7.6.9
      - proxy-tools==0.1.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pyhdfe==0.2.0
      - pyjwt==2.10.1
      - pyluach==2.2.0
      - pytest==8.3.4
      - pytest-freezegun==0.4.2
      - python-dotenv==1.0.1
      - python-interface==1.6.1
      - python-multipart==0.0.18
      - pytimetk==1.2.3
      - pywebview==5.4
      - random-user-agent==1.0.1
      - requests-cache==1.2.1
      - ruff==0.7.4
      - setuptools-scm==8.1.0
      - sqlalchemy==2.0.36
      - starlette==0.45.3
      - supersmoother==0.4
      - tiingo==0.15.6
      - timebasedcv==0.3.0
      - tld==0.13
      - trafilatura==2.0.0
      - tsfeatures==0.4.5
      - url-normalize==1.4.3
      - uuid7==0.1.0
      - uvicorn==0.34.0
      - websockets==14.2
      - xarray==2025.3.1
      - xlrd==2.0.1
      - xmltodict==0.13.0
      - zipline-reloaded==3.1
